version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: auth-process
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: carrierwave-base64
    versions:
    - 2.10.0
  - dependency-name: listen
    versions:
    - 3.5.0
    - 3.5.1
  - dependency-name: carrierwave
    versions:
    - 2.1.1
    - 2.2.0
    - 2.2.1
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: bootsnap
    versions:
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: puma
    versions:
    - 5.2.2
